R* = { [[ L ";" | A ";" ]] } ;
A = D "=" S ;
L = E ;

E = "[" #ID {{ "elem("*")" ; }} { "," #ID {{ "elem("*")" ; }} } "]" ;
D = "[" #ID {{ "dest("*")" ; }} { "," #ID {{ "dest("*")" ; }} } "]" ;
S = "[" #ID {{ "srce("*")" ; }} { "," #ID {{ "srce("*")" ; }} } "]" ;

.
