!
! json's grammar.
!

object* = "{" [ pairs ] "}" ;
pairs = pair { "," pair } ;
pair = #STR2 ":" value ;
value = #STR2 | #NUM | "true" | "false" | "null" | object | array ;
array = "[" [ elements ] "]" ;
elements = value { "," value } ;

.
